ARG IMAGE=mcr.microsoft.com
ARG IMAGE_TAG=1.0
FROM ${IMAGE}:${TAG}

USER ContainerUser

ARG EXE_DIR=.

WORKDIR /app

COPY $EXE_DIR/ ./

ENV IPInterfaceName vEthernet (Ethernet)

CMD ["GPIOFruit.exe"]
